---
- name: "Controller : RabbitMQ 설치 ~~~~~~~~~~~~~~!!!"
  hosts: remotes
  become: yes
  any_errors_fatal: true

  tasks:
    - name: "<Controller:APT> Install rabbitmq-server"
      apt:
        name: rabbitmq-server
        state: present
      when: hostname == 'controller'

    - name: Restart rabbitmq-server service
      service:
        name: rabbitmq-server
        state: restarted
      when: hostname == 'controller'

    - name: "rabbitmqctl add_user openstack"
      command: rabbitmqctl add_user openstack {{STACK_PASSWD}}
      register: command_output
      when: hostname == 'controller'

    - name: Show command output
      debug:
        var: command_output.stdout
      when: hostname == 'controller'

    - name: "rabbitmqctl set_permissions"
      command: rabbitmqctl set_permissions openstack ".*" ".*" ".*"
      register: command_output
      when: hostname == 'controller'

    - name: Show command output
      debug:
        var: command_output.stdout
      when: hostname == 'controller'