---
- name: "Controller : NTP 설치 !!"
  hosts: remotes
  become: yes
  any_errors_fatal: true

  tasks:
    - name: Install chrony
      apt:
        name: chrony
        state: present
        update_cache: yes
      when: hostname == 'controller'

    - name: Add server to chrony.conf
      lineinfile:
        path: /etc/chrony/chrony.conf
        line: "server {{inventory_hostname}} iburst"
        create: yes
      when: hostname == 'controller'

    - name: Add allow rule to chrony.conf
      lineinfile:
        path: /etc/chrony/chrony.conf
        line: "allow {{SET_IP_ALLOW}}"
        create: yes
      when: hostname == 'controller'

    - name: Restart chrony service
      service:
        name: chrony
        state: restarted
      when: hostname == 'controller'

    - name: Check chrony sources
      command: chronyc sources
      register: chronyc_sources_first
      failed_when: false
      when: hostname == 'controller'

    - debug:
        msg:
          - "Chrony sources check: {{ chronyc_sources_first.stdout_lines }}"
      when: hostname == 'controller' 