---
- name: 시스템 재시작 !!
  hosts: remotes
  become: yes
  any_errors_fatal: true
  
  tasks:
    - name: "<remotes:System> Reboot"
      reboot:
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 15
